### ISSUE TITLE
Missing attributes in events stream

### ISSUE THREAD

**Issue by cirotix** [singer-io/tap-chargify#25]
The `events` stream has an `event_specific_data` property that has a different schema for each type of event.

Currently only the attributes `product_id` and `account_transaction_id` are declared. That means that all the attributes for the other type of event will be ignored (see https://reference.chargify.com/v1/events/events-intro#events-fields-and-event-type for the type of event). 

Chargify does not publish the schema for each event type. However, I am speaking with them to have it and will submit a PR with the full specification.

**Comment by zachharris1** [comment]
Was this issue resolved by #28 (which was merged into master via #31 )? If thats the case, this issue is resolved.

**Comment by cirotix** [comment]
Yes it was resolved by #28 / #31. I am not 100% sure the all the events properties have been added (still waiting for Chargify official schema) but this issue can be closed. I will open a new PR should there are some missing properties when I will have an answer from Chargify.
